services:
  iam:
    build: .
    depends_on:
      iam_database:
        condition: service_healthy
      iam_migrations:
        condition: service_completed_successfully
    environment:
      SERVER_ADDRESS: "0.0.0.0:3000"
      DATABASE_URL: postgres://postgres:postgres@iam_database:5432/iam_db?sslmode=disable
      JWT_SECRET: iPSYsdBlq0wHCsIlJ80XCJALSlld1kzl9A64bHtwdX3OdkNwFe6utHv3d57l9cHpnMBoQ5T5GzCo0VszeaBqzO
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    networks:
      - distributed-workflow

  iam_migrations:
    build: .
    depends_on:
      iam_database:
        condition: service_healthy
    environment:
      GOOSE_DBSTRING: postgres://postgres:postgres@iam_database:5432/iam_db?sslmode=disable
      GOOSE_DRIVER: postgres
      GOOSE_MIGRATION_DIR: /app/migrations
      GOOSE_TABLE: goose_migrations
    volumes:
      - ./migrations:/app/migrations
    networks:
      - distributed-workflow
    command: go tool goose up

  iam_database:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_DB: iam_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - iam_data:/var/lib/postgresql
    networks:
      - distributed-workflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
